#pod 源
source 'https://github.com/CocoaPods/Specs.git'
#私有pod
source 'http://gitlab.meishubao.com/ArtPods/ArtPodRepo.git'
#aliyun
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'
workspace 'NIM.xcworkspace'

abstract_target 'NIMDemo' do
    pod 'SDWebImage', '~> 5.0.6'
    pod 'SDWebImageFLPlugin', '~> 0.3.0'
    pod 'Toast', '~> 3.0'
    pod 'M80AttributedLabel', '~> 1.9.9'
    pod 'TZImagePickerController', '~> 3.2.1'
    pod 'YYImage'
    pod 'YYImage/WebP'
    pod 'AFNetworking'
    pod 'Masonry', '~> 1.0.2'
    pod 'ReactiveCocoa', '~> 2.5.2'
    pod 'YYText', '~> 1.0.7'
    
    pod 'ArtLoginAndRegister', '0.0.3.3'
    pod 'ArtFoundation' , '0.0.9.1'
    pod 'ArtCommon', '1.0.13.11'
    pod 'ArtLogger', '0.3.4.8'


    target 'NIM' do
        project 'NIM.xcodeproj'
        pod 'FMDB', '~> 2.7.2'
        pod 'Reachability', '~> 3.2'
        pod 'CocoaLumberjack', '~> 3.2.1'
        pod 'SSZipArchive', '~> 1.8.1'
        pod 'SVProgressHUD', '~> 2.1.2'
        pod 'Fabric'
        pod 'Crashlytics'
    end
    
    target 'NIMKit' do
        project '../NIMKit/NIMKit.xcodeproj'
    end
end

